extend type Club {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Club", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Club`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Club.user", purpose: IMPLICIT_REF_FIELD)
}
extend type ClubObservation {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ClubObservation", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `ClubObservation`.`club`. It must match the value of `Club`.`id`. See `@ref` for how to customize it.
  """
  clubId: UUID! @fdc_generated(from: "ClubObservation.club", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `ClubObservation`.`golfRound`. It must match the value of `GolfRound`.`id`. See `@ref` for how to customize it.
  """
  golfRoundId: UUID! @fdc_generated(from: "ClubObservation.golfRound", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `ClubObservation`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "ClubObservation.user", purpose: IMPLICIT_REF_FIELD)
}
extend type GolfRound {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "GolfRound", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `GolfRound`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "GolfRound.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
