extend type Query {
  """
  ✨ Look up a single `Club` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  club(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Club_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Club_FirstRow
  ): Club @fdc_generated(from: "Club", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ClubObservation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  clubObservation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClubObservation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClubObservation_FirstRow
  ): ClubObservation @fdc_generated(from: "ClubObservation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `GolfRound` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  golfRound(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GolfRound_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GolfRound_FirstRow
  ): GolfRound @fdc_generated(from: "GolfRound", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Club` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  clubs(
    """
    Filter condition to narrow down the query results.
    """
    where: Club_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Club_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Club_Having
  ): [Club!]! @fdc_generated(from: "Club", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ClubObservation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  clubObservations(
    """
    Filter condition to narrow down the query results.
    """
    where: ClubObservation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ClubObservation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ClubObservation_Having
  ): [ClubObservation!]! @fdc_generated(from: "ClubObservation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `GolfRound` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  golfRounds(
    """
    Filter condition to narrow down the query results.
    """
    where: GolfRound_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GolfRound_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GolfRound_Having
  ): [GolfRound!]! @fdc_generated(from: "GolfRound", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
